INCLUDE(ExternalProject)

SET(ZLIB_PREFIX_DIR ${CC_BINARY_DIR}/zlib)
SET(ZLIB_SOURCE_DIR ${CC_BINARY_DIR}/zlib/src/extern_zlib)
SET(ZLIB_INSTALL_DIR ${CC_BINARY_DIR}/zlib/install/zlib)
SET(ZLIB_INCLUDE_DIR "${ZLIB_INSTALL_DIR}/include" CACHE PATH "zlib include directory." FORCE)
set(ZLIB_REPOSITORY https://github.com/madler/zlib.git)
set(ZLIB_TAG        v1.3)

IF(MSVC)
  SET(MSVC_RUN_TIME -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING=MultiThreaded)
ENDIF()

IF(WIN32)
  SET(ZLIB_STATIC_LIB ${ZLIB_INSTALL_DIR}/lib/zlibstatic.lib)
ELSE()
  SET(ZLIB_STATIC_LIB ${ZLIB_INSTALL_DIR}/lib/libz.a)
ENDIF()

ExternalProject_Add(
    extern_zlib
    GIT_REPOSITORY ${ZLIB_REPOSITORY}
    GIT_TAG ${ZLIB_TAG}
    PREFIX          ${ZLIB_PREFIX_DIR}
    SOURCE_DIR      ${ZLIB_SOURCE_DIR}
    UPDATE_COMMAND  ""
    BUILD_BYPRODUCTS ${ZLIB_STATIC_LIB}
    CMAKE_ARGS      -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
                    -DCMAKE_BUILD_TYPE=RelWithDebInfo
                    -DCMAKE_INSTALL_PREFIX=${ZLIB_INSTALL_DIR}
                    -DBUILD_SHARED_LIBS=ON
                    -DCMAKE_POSITION_INDEPENDENT_CODE=ON
                    -DCMAKE_MACOSX_RPATH=ON
                    ${MSVC_RUN_TIME}
                    -DCMAKE_VERBOSE_MAKEFILE=ON
    CMAKE_CACHE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${ZLIB_INSTALL_DIR}
                     -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
#                     -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
)

ADD_LIBRARY(zlib STATIC IMPORTED GLOBAL)
ADD_DEPENDENCIES(zlib extern_zlib)
SET_TARGET_PROPERTIES(zlib PROPERTIES IMPORTED_LOCATION ${ZLIB_STATIC_LIB})
SET(ZLIB_FOUND 1)
